"""데이터베이스 연결과 스키마.

환경변수 DATABASE_URL 이 있으면 Supabase(Postgres)에, 없으면 instance/housing.db(SQLite)에 저장한다.
SQL은 두 데이터베이스에서 모두 동작하도록 작성하고, 자리표시자는 '?'로 통일한다.
"""
import os
import sqlite3

from flask import g

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
IS_PG = DATABASE_URL.startswith(("postgres://", "postgresql://"))

_TYPES = {
    "pk": "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" if IS_PG else "INTEGER PRIMARY KEY",
    "real": "DOUBLE PRECISION" if IS_PG else "REAL",
    "now": "(to_char(now() AT TIME ZONE 'Asia/Seoul', 'YYYY-MM-DD HH24:MI:SS'))" if IS_PG
           else "(datetime('now','localtime'))",
}

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id {pk},
    username TEXT NOT NULL UNIQUE,
    pw_hash TEXT NOT NULL,
    name TEXT,
    is_admin INTEGER NOT NULL DEFAULT 0,
    created TEXT DEFAULT {now}
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

-- 빌라(건물)
CREATE TABLE IF NOT EXISTS buildings (
    id {pk},
    code TEXT,
    name TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT '빌라',
    address TEXT,
    zip TEXT,
    owner_name TEXT,
    owner_phone TEXT,
    manager TEXT,
    elec_no TEXT,
    water_no TEXT,
    gas_no TEXT,
    -- 공과금 부과 방식: none(부과안함) / price(사용량x단가) / ratio(사용량 비율 배분) / equal(세대 균등)
    elec_method TEXT NOT NULL DEFAULT 'none',
    water_method TEXT NOT NULL DEFAULT 'ratio',
    gas_method TEXT NOT NULL DEFAULT 'none',
    common_method TEXT NOT NULL DEFAULT 'none',
    bill_rent INTEGER NOT NULL DEFAULT 0,
    memo TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created TEXT DEFAULT {now}
);

-- 세대(호수)
CREATE TABLE IF NOT EXISTS units (
    id {pk},
    building_id INTEGER NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
    ho TEXT NOT NULL,
    tenant TEXT,
    phone TEXT,
    mobile TEXT,
    move_in TEXT,
    move_out TEXT,
    status TEXT NOT NULL DEFAULT '입주',
    deposit BIGINT NOT NULL DEFAULT 0,
    rent BIGINT NOT NULL DEFAULT 0,
    auto_transfer INTEGER NOT NULL DEFAULT 0,
    memo TEXT,
    UNIQUE (building_id, ho)
);

-- 관리비 항목 마스터
CREATE TABLE IF NOT EXISTS fee_items (
    id {pk},
    name TEXT NOT NULL UNIQUE,
    sort INTEGER NOT NULL DEFAULT 0,
    active INTEGER NOT NULL DEFAULT 1
);

-- 빌라별 항목 금액. method: unit(세대당 금액) / split(총액을 입주세대로 분할)
CREATE TABLE IF NOT EXISTS building_fees (
    building_id INTEGER NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES fee_items(id) ON DELETE CASCADE,
    amount BIGINT NOT NULL DEFAULT 0,
    method TEXT NOT NULL DEFAULT 'unit',
    PRIMARY KEY (building_id, item_id)
);

-- 세대별 항목 금액(빌라 기본값 대신 사용)
CREATE TABLE IF NOT EXISTS unit_fees (
    unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES fee_items(id) ON DELETE CASCADE,
    amount BIGINT NOT NULL,
    PRIMARY KEY (unit_id, item_id)
);

-- 검침 (util: elec/water/gas)
CREATE TABLE IF NOT EXISTS readings (
    unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE CASCADE,
    ym TEXT NOT NULL,
    util TEXT NOT NULL,
    prev {real},
    curr {real},
    PRIMARY KEY (unit_id, ym, util)
);

-- 빌라 전체 고지금액 (한전/수도사업소/가스회사) 및 단가 (util: elec/water/gas/common)
CREATE TABLE IF NOT EXISTS building_bills (
    building_id INTEGER NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
    ym TEXT NOT NULL,
    util TEXT NOT NULL,
    amount BIGINT NOT NULL DEFAULT 0,
    unit_price {real} NOT NULL DEFAULT 0,
    PRIMARY KEY (building_id, ym, util)
);

-- 고지(부과) 내역. kind: normal(월 관리비) / carry(이월 미납)
CREATE TABLE IF NOT EXISTS bills (
    id {pk},
    unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE CASCADE,
    ym TEXT NOT NULL,
    kind TEXT NOT NULL DEFAULT 'normal',
    amount BIGINT NOT NULL,
    late_fee BIGINT NOT NULL DEFAULT 0,
    due_date TEXT NOT NULL,
    issued TEXT,
    memo TEXT,
    UNIQUE (unit_id, ym, kind)
);

CREATE TABLE IF NOT EXISTS bill_lines (
    id {pk},
    bill_id INTEGER NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    amount BIGINT NOT NULL,
    detail TEXT,
    sort INTEGER NOT NULL DEFAULT 0
);

-- 수납
CREATE TABLE IF NOT EXISTS payments (
    id {pk},
    unit_id INTEGER NOT NULL REFERENCES units(id) ON DELETE CASCADE,
    pay_date TEXT NOT NULL,
    amount BIGINT NOT NULL,
    method TEXT,
    payer TEXT,
    memo TEXT,
    created TEXT DEFAULT {now}
);

-- 수납액을 고지 건에 배정한 내역 (오래된 고지부터 자동 배정)
CREATE TABLE IF NOT EXISTS allocations (
    payment_id INTEGER NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    bill_id INTEGER NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    amount BIGINT NOT NULL
);

-- 엑셀 가져오기 미리보기 임시 보관
CREATE TABLE IF NOT EXISTS import_jobs (
    token TEXT PRIMARY KEY,
    data TEXT NOT NULL,
    created TEXT DEFAULT {now}
);

CREATE INDEX IF NOT EXISTS idx_units_building ON units(building_id);
CREATE INDEX IF NOT EXISTS idx_bills_unit ON bills(unit_id, ym);
CREATE INDEX IF NOT EXISTS idx_bill_lines_bill ON bill_lines(bill_id);
CREATE INDEX IF NOT EXISTS idx_readings_unit ON readings(unit_id, util, ym);
CREATE INDEX IF NOT EXISTS idx_payments_unit ON payments(unit_id, pay_date);
CREATE INDEX IF NOT EXISTS idx_alloc_bill ON allocations(bill_id);
CREATE INDEX IF NOT EXISTS idx_alloc_payment ON allocations(payment_id);
""".format(**_TYPES)

TABLES = ["users", "settings", "buildings", "units", "fee_items", "building_fees", "unit_fees", "readings",
          "building_bills", "bills", "bill_lines", "payments", "allocations", "import_jobs"]

DEFAULT_SETTINGS = {
    "company_name": "",
    "company_phone": "",
    "company_address": "",
    "bank_info": "",
    "late_rate": "2",
    "round_unit": "10",
    "round_mode": "floor",
    "due_offset": "1",
    "due_day": "25",
    "notice": "납부마감일까지 납부해 주시기 바랍니다. 입금 시 입금자명을 '빌라명+호수'로 적어 주세요.",
    "dunning_text": "귀댁의 관리비가 아래와 같이 체납되어 있습니다. 체납이 계속되면 제반 업무 수행에 지장이 있으니 기일 내 납부해 주시기 바랍니다.",
}

DEFAULT_FEE_ITEMS = ["일반관리비", "청소비", "수선유지비", "승강기유지비", "정화조", "인터넷", "유선방송", "기타"]


# ---------------------------------------------------------------- Postgres 연결

class Row(dict):
    """sqlite3.Row 처럼 이름(row['ho'])과 순서(row[0]) 모두로 읽을 수 있는 행."""
    __slots__ = ("_values",)

    def __init__(self, names, values):
        super().__init__(zip(names, values))
        self._values = values

    def __getitem__(self, key):
        return self._values[key] if isinstance(key, int) else dict.__getitem__(self, key)


def _row_factory(cursor):
    names = [c.name for c in cursor.description] if cursor.description else []
    return lambda values: Row(names, values)


class PgConn:
    """'?' 자리표시자를 쓰는 SQL을 psycopg 형식으로 바꿔 실행하는 얇은 래퍼."""

    def __init__(self, conn):
        self.conn = conn

    def execute(self, sql, params=()):
        return self.conn.execute(sql.replace("%", "%%").replace("?", "%s"), tuple(params))

    def commit(self):
        self.conn.commit()

    def rollback(self):
        self.conn.rollback()


def connect_pg():
    import psycopg
    # 서버리스(Vercel)에서는 요청마다 새로 연결한다. 연결 재사용은 Supabase 연결 풀러가 맡는다.
    # prepare_threshold=None: 풀러(트랜잭션 모드)에서는 준비된 문장을 쓸 수 없으므로 끈다.
    return psycopg.connect(DATABASE_URL, row_factory=_row_factory, prepare_threshold=None, connect_timeout=10)


# ---------------------------------------------------------------- 공통

def connect_sqlite(path):
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def get_db():
    if "db" not in g:
        if IS_PG:
            g.pg_raw = connect_pg()
            g.db = PgConn(g.pg_raw)
        else:
            from flask import current_app
            g.db = connect_sqlite(os.path.join(current_app.instance_path, "housing.db"))
    return g.db


def close_db(_exc=None):
    conn = g.pop("db", None)
    if conn is None:
        return
    if IS_PG:
        raw = g.pop("pg_raw")
        raw.close()  # 커밋하지 않은 작업은 버려진다
    else:
        conn.close()


def init_db(sqlite_path):
    if IS_PG:
        with connect_pg() as raw:
            conn = PgConn(raw)
            for stmt in SCHEMA.split(";"):
                if stmt.strip():
                    raw.execute(stmt)
            # Supabase는 public 테이블을 API로 노출하므로 RLS를 켜서 외부 API 접근을 막는다(서버 연결은 영향 없음)
            for t in TABLES:
                raw.execute(f"ALTER TABLE {t} ENABLE ROW LEVEL SECURITY")
            _seed(conn)
            raw.commit()
    else:
        conn = connect_sqlite(sqlite_path)
        conn.executescript(SCHEMA)
        _seed(conn)
        conn.commit()
        conn.close()


def _seed(conn):
    for k, v in DEFAULT_SETTINGS.items():
        conn.execute("INSERT INTO settings(key, value) VALUES (?, ?) ON CONFLICT (key) DO NOTHING", (k, v))
    if conn.execute("SELECT COUNT(*) FROM fee_items").fetchone()[0] == 0:
        for i, name in enumerate(DEFAULT_FEE_ITEMS):
            conn.execute("INSERT INTO fee_items(name, sort) VALUES (?, ?)", (name, i))


def get_settings(conn):
    return {r["key"]: r["value"] for r in conn.execute("SELECT key, value FROM settings")}
